server:
  port: 8090

spring:
  application:
    name: msvc-task
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect 
  config:
    import: optional:configserver:http://localhost:8888
    hibernate:
      ddl-auto: create

eureka: 
  instance: 
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
