server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: microservice-apigateway 
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: microservice-task
          uri: lb://microservice-task
          predicates:
            - Path=/microservice-task/**
        - id: static-content
          uri: lb://microservice-task
          predicates:
            - Path=/css/**
        - id: change-state-task
          uri: lb://microservice-task
          predicates:
            - Path=/changeStateTask
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id:
      hostname: localhost
    

